spring:
  redis:
    password: 3Q3Q
    sentinel:
      master: mymaster
      nodes:
        - 192.168.8.128:26380
        - 192.168.8.129:26380
        - 192.168.8.130:26380
    lettuce:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10









































