spring:
  redis:
    host: 192.168.145.11
    port: 6380
    password: 3Q3Q
    database: 12
    timeout: 4000
    lettuce:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10





































