spring:
  redis:
    host: 192.168.101.129
    port: 6380
    password: 3Q3Q
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10





































