spring:
  redis:
    password: 3Q3Q
    timeout: 5000
    database: 0
    cluster:
      nodes:
        - 192.168.8.128:6391
        - 192.168.8.128:6392
        - 192.168.8.129:6393
        - 192.168.8.129:6394
        - 192.168.8.130:6395
        - 192.168.8.130:6396
      max-redirects: 3
    lettuce:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10









































