spring:
  redis:
    master:
      host: 192.168.145.11
      port: 6381
      password: 3Q3Q
      database: 0
      timeout: 4000
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10
    slave:
      host: 192.168.145.11
      port: 6382
      password: 3Q3Q
      database: 0
      timeout: 4000
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10







































