spring:
  redis:
    password: 3Q3Q
    sentinel:
      master: mymaster
      nodes: 192.168.145.11:26381,192.168.145.11:26382,192.168.145.11:26383
    lettuce:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: 20
        min-idle: 10









































